// A real bytes32 poolId (keccak256 output) matching this value is astronomically unlikely — used
// as a "match nothing" placeholder so an empty whitelist means "index no V4 swaps yet" rather than
// an empty `where.params` array whose match semantics against real HyperSync queries are unverified.
const NEVER_MATCHES = `0x${'0'.repeat(64)}`;

export function renderV4PoolWhitelistModule(poolIds: readonly string[]): string {
  const normalized = [...new Set(poolIds.map((id) => id.toLowerCase()))].sort();
  const entries = normalized.length > 0 ? normalized : [NEVER_MATCHES];
  const lines = entries.map((id) => `  '${id}',`).join('\n');
  return `// Generated by \`npm run export:v4-pool-whitelist -w be\` — do not edit by hand.
// Static whitelist of Pons-graduated Uniswap V4 pool IDs (be/src/db/schema.ts's venues table,
// kind='v4_pool' AND official=true). UniswapV4PoolManager is one contract shared by every V4 pool
// on the chain; this is the only filter mechanism Envio supports for a non-address indexed param
// (verified: dynamic where-filter growth only works for address-typed params, not bytes32 poolId).
// Regenerate and restart the envio-indexer container after a new launch graduates to V4 — see
// README.md's "Danh sách pool V4 whitelist" section for the exact steps and the known gap window.
export const KNOWN_PONS_V4_POOL_IDS: readonly string[] = [
${lines}
];
`;
}
