/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                chainId?: number;
                                tokenAddress?: string;
                                name?: string;
                                symbol?: string;
                                platform?: string;
                                protocolVersion?: string;
                                quoteAsset?: {
                                    address?: string;
                                    symbol?: string;
                                    decimals?: number;
                                };
                                lifecycleStatus?: string;
                                officialVolume24h?: string | null;
                                coverageStatus?: string;
                                fdvUsd?: string | null;
                                marketCapUsd?: string | null;
                                tvlUsd?: string | null;
                                tvlBasis?: string | null;
                                tvlBlockNumber?: string | null;
                                tvlPriceSource?: string | null;
                                tvlPriceUpdatedAt?: number | null;
                                tvlUnavailableReason?: string | null;
                                week52High?: string | null;
                                week52Low?: string | null;
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chainId?: number;
                            tokenAddress?: string;
                            name?: string;
                            symbol?: string;
                            platform?: string;
                            protocolVersion?: string;
                            quoteAsset?: {
                                address?: string;
                                symbol?: string;
                                decimals?: number;
                            };
                            lifecycleStatus?: string;
                            officialVolume24h?: string | null;
                            coverageStatus?: string;
                            fdvUsd?: string | null;
                            marketCapUsd?: string | null;
                            tvlUsd?: string | null;
                            tvlBasis?: string | null;
                            tvlBlockNumber?: string | null;
                            tvlPriceSource?: string | null;
                            tvlPriceUpdatedAt?: number | null;
                            tvlUnavailableReason?: string | null;
                            week52High?: string | null;
                            week52Low?: string | null;
                            officialVenues?: {
                                id?: string;
                                kind?: string;
                                ref?: string;
                                effectiveFromBlock?: string;
                                effectiveToBlock?: string | null;
                            }[];
                            priceQuote?: string | null;
                            priceStale?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                venueId?: string;
                                blockNumber?: string;
                                txHash?: string;
                                logIndex?: number;
                                timestamp?: number;
                                side?: string;
                                activityKind?: string;
                                tokenAmount?: string;
                                quoteAmount?: string;
                                priceQuote?: string | null;
                                traderAddress?: string;
                                usdValue?: string | null;
                                usdValueApprox?: boolean;
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                intervalSeconds?: number;
                                bucketStart?: number;
                                open?: string;
                                high?: string;
                                low?: string;
                                close?: string;
                                quoteVolume?: string;
                            }[];
                            complete?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
