/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            complete?: boolean;
                            pendingSourceIds?: string[];
                            missingRanges?: {
                                sourceId?: string;
                                fromBlock?: string;
                                toBlock?: string;
                                reason?: string;
                            }[];
                            latestFinalizedFence?: string | null;
                            launchParity?: {
                                sourceId?: string;
                                /** @enum {string} */
                                status?: "complete" | "mismatch" | "pending" | "unverified";
                                auditedToBlock?: string | null;
                                finalizedTargetBlock?: string | null;
                                envioWatermark?: string | null;
                                appWatermark?: string | null;
                            }[];
                            parityAlerts?: {
                                mismatchedSources?: number;
                                stalledSources?: number;
                                pendingRepairs?: number;
                            };
                            incrementalSync?: {
                                observedEnvioHead?: string | null;
                                tailConfirmedBlock?: string | null;
                                historyConfirmedBlock?: string | null;
                                tailLagBlocks?: string | null;
                                historyBacklogBlocks?: string | null;
                                unresolvedEventCount?: number;
                                pendingCoreMetadataCount?: number;
                                repair?: {
                                    lastRunAt?: string | null;
                                    lastSuccessAt?: string | null;
                                    lastFailureAt?: string | null;
                                    lastFailureReason?: string | null;
                                    failureCount?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                token?: {
                                    chainId?: number;
                                    tokenAddress?: string;
                                    name?: string | null;
                                    symbol?: string | null;
                                    logoUri?: string | null;
                                };
                                venueId?: string;
                                blockNumber?: string;
                                txHash?: string;
                                logIndex?: number;
                                timestamp?: number;
                                side?: string;
                                activityKind?: string;
                                tokenAmount?: string | null;
                                quoteAmount?: string | null;
                                quoteAsset?: {
                                    address?: string;
                                    symbol?: string | null;
                                };
                                traderAddress?: string;
                                usdValue?: string | null;
                                usdValueApprox?: boolean;
                                /** @enum {string} */
                                usdValueStatus?: "priced" | "pending" | "unavailable";
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                chainId?: number;
                                tokenAddress?: string;
                                name?: string | null;
                                symbol?: string | null;
                                platform?: string;
                                protocolVersion?: string;
                                quoteAsset?: {
                                    address?: string;
                                    symbol?: string | null;
                                    decimals?: number | null;
                                };
                                tokenDecimals?: number | null;
                                lifecycleStatus?: string;
                                officialVolume24h?: string | null;
                                coverageStatus?: string;
                                fdvUsd?: string | null;
                                marketCapUsd?: string | null;
                                priceUsd?: string | null;
                                tvlUsd?: string | null;
                                tvlBasis?: string | null;
                                tvlBlockNumber?: string | null;
                                tvlPriceSource?: string | null;
                                tvlPriceUpdatedAt?: number | null;
                                tvlUnavailableReason?: string | null;
                                week52High?: string | null;
                                week52Low?: string | null;
                                logoUri?: string | null;
                                websiteUrl?: string | null;
                                twitterUrl?: string | null;
                                launchTimestamp?: string | null;
                                change1h?: string | null;
                                change1d?: string | null;
                                officialVolume24hUsd?: string | null;
                                officialVolume24hUsdApprox?: boolean;
                                /** Format: date-time */
                                officialVolume24hUsdAsOf?: string | null;
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chainId?: number;
                            tokenAddress?: string;
                            name?: string | null;
                            symbol?: string | null;
                            platform?: string;
                            protocolVersion?: string;
                            quoteAsset?: {
                                address?: string;
                                symbol?: string | null;
                                decimals?: number | null;
                            };
                            tokenDecimals?: number | null;
                            lifecycleStatus?: string;
                            officialVolume24h?: string | null;
                            coverageStatus?: string;
                            fdvUsd?: string | null;
                            marketCapUsd?: string | null;
                            priceUsd?: string | null;
                            tvlUsd?: string | null;
                            tvlBasis?: string | null;
                            tvlBlockNumber?: string | null;
                            tvlPriceSource?: string | null;
                            tvlPriceUpdatedAt?: number | null;
                            tvlUnavailableReason?: string | null;
                            week52High?: string | null;
                            week52Low?: string | null;
                            logoUri?: string | null;
                            websiteUrl?: string | null;
                            twitterUrl?: string | null;
                            launchTimestamp?: string | null;
                            change1h?: string | null;
                            change1d?: string | null;
                            officialVolume24hUsd?: string | null;
                            officialVolume24hUsdApprox?: boolean;
                            /** Format: date-time */
                            officialVolume24hUsdAsOf?: string | null;
                            description?: string | null;
                            officialVenues?: {
                                id?: string;
                                kind?: string;
                                ref?: string;
                                effectiveFromBlock?: string;
                                effectiveToBlock?: string | null;
                            }[];
                            priceQuote?: string | null;
                            priceStale?: boolean;
                            quotePriceUsd?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                venueId?: string;
                                blockNumber?: string;
                                txHash?: string;
                                logIndex?: number;
                                timestamp?: number;
                                side?: string;
                                activityKind?: string;
                                tokenAmount?: string | null;
                                quoteAmount?: string | null;
                                priceQuote?: string | null;
                                traderAddress?: string;
                                usdValue?: string | null;
                                usdValueApprox?: boolean;
                                /** @enum {string} */
                                usdValueStatus?: "priced" | "pending" | "unavailable";
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                /** @enum {string} */
                                source?: "official" | "pool";
                                venueId?: string | null;
                                pool?: {
                                    protocol?: string;
                                    poolId?: string;
                                } | null;
                                blockNumber?: string;
                                txHash?: string;
                                logIndex?: number;
                                timestamp?: number;
                                side?: string;
                                activityKind?: string | null;
                                tokenAmount?: string | null;
                                quoteAmount?: string | null;
                                quoteAssetAddress?: string | null;
                                traderAddress?: string;
                                usdValue?: string | null;
                                usdValueApprox?: boolean;
                                /** @enum {string} */
                                usdValueStatus?: "priced" | "pending" | "unavailable";
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                intervalSeconds?: number;
                                bucketStart?: number;
                                open?: string;
                                high?: string;
                                low?: string;
                                close?: string;
                                quoteVolume?: string;
                                volumeUsd?: string;
                                tradeCount?: number;
                                /** Format: date-time */
                                computedAt?: string;
                            }[];
                            complete?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                chainId?: number;
                                protocol?: string;
                                poolId?: string;
                                currency0?: string;
                                currency1?: string;
                                displayedToken?: string;
                                currency0Symbol?: string | null;
                                currency0Name?: string | null;
                                currency0LogoUri?: string | null;
                                currency0Decimals?: number | null;
                                currency1Symbol?: string | null;
                                currency1Name?: string | null;
                                currency1LogoUri?: string | null;
                                currency1Decimals?: number | null;
                                fee?: number;
                                tickSpacing?: number;
                                hooks?: string;
                                createdBlock?: string;
                                createdTimestamp?: number | null;
                                ponsDesignated?: boolean;
                                poolBalances?: {
                                    displayedAmountRaw: string;
                                    otherAmountRaw: string;
                                    priceInQuote: string;
                                } | null;
                                launchTokenAddress?: string | null;
                                volume24hUsd?: string | null;
                                volume24hChange?: string | null;
                                priceInQuote?: string | null;
                                priceUsd?: string | null;
                                fdvUsd?: string | null;
                                tvlUsd?: string | null;
                                tvlChange?: string | null;
                                change1h?: string | null;
                                change1d?: string | null;
                                coverageStatus?: string;
                                lastTradeTimestamp?: number | null;
                            }[];
                            nextCursor?: string | null;
                            supportedProtocols?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/launches/{chainId}/{tokenAddress}/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    tokenAddress: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                chainId?: number;
                                protocol?: string;
                                poolId?: string;
                                currency0?: string;
                                currency1?: string;
                                displayedToken?: string;
                                currency0Symbol?: string | null;
                                currency0Name?: string | null;
                                currency0LogoUri?: string | null;
                                currency0Decimals?: number | null;
                                currency1Symbol?: string | null;
                                currency1Name?: string | null;
                                currency1LogoUri?: string | null;
                                currency1Decimals?: number | null;
                                fee?: number;
                                tickSpacing?: number;
                                hooks?: string;
                                createdBlock?: string;
                                createdTimestamp?: number | null;
                                ponsDesignated?: boolean;
                                poolBalances?: {
                                    displayedAmountRaw: string;
                                    otherAmountRaw: string;
                                    priceInQuote: string;
                                } | null;
                                launchTokenAddress?: string | null;
                                volume24hUsd?: string | null;
                                volume24hChange?: string | null;
                                priceInQuote?: string | null;
                                priceUsd?: string | null;
                                fdvUsd?: string | null;
                                tvlUsd?: string | null;
                                tvlChange?: string | null;
                                change1h?: string | null;
                                change1d?: string | null;
                                coverageStatus?: string;
                                lastTradeTimestamp?: number | null;
                            }[];
                            nextCursor?: string | null;
                            supportedProtocols?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pools/{chainId}/{protocol}/{poolId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    protocol: string;
                    poolId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chainId?: number;
                            protocol?: string;
                            poolId?: string;
                            currency0?: string;
                            currency1?: string;
                            displayedToken?: string;
                            currency0Symbol?: string | null;
                            currency0Name?: string | null;
                            currency0LogoUri?: string | null;
                            currency0Decimals?: number | null;
                            currency1Symbol?: string | null;
                            currency1Name?: string | null;
                            currency1LogoUri?: string | null;
                            currency1Decimals?: number | null;
                            fee?: number;
                            tickSpacing?: number;
                            hooks?: string;
                            createdBlock?: string;
                            createdTimestamp?: number | null;
                            ponsDesignated?: boolean;
                            poolBalances?: {
                                displayedAmountRaw: string;
                                otherAmountRaw: string;
                                priceInQuote: string;
                            } | null;
                            launchTokenAddress?: string | null;
                            volume24hUsd?: string | null;
                            volume24hChange?: string | null;
                            priceInQuote?: string | null;
                            priceUsd?: string | null;
                            fdvUsd?: string | null;
                            tvlUsd?: string | null;
                            tvlChange?: string | null;
                            change1h?: string | null;
                            change1d?: string | null;
                            coverageStatus?: string;
                            lastTradeTimestamp?: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pools/{chainId}/{protocol}/{poolId}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    protocol: string;
                    poolId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                txHash?: string;
                                logIndex?: number;
                                blockNumber?: string;
                                timestamp?: number;
                                traderAddress?: string;
                                side?: string;
                                amount0Raw?: string;
                                amount1Raw?: string;
                                priceInQuote?: string | null;
                                usdValue?: string | null;
                                /** @enum {string} */
                                usdValueStatus?: "priced" | "pending" | "unavailable";
                            }[];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pools/{chainId}/{protocol}/{poolId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    protocol: string;
                    poolId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                day?: number;
                                tradeCount?: number;
                                volumeUsd?: string | null;
                                tvlUsd?: string | null;
                            }[];
                            complete?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pools/{chainId}/{protocol}/{poolId}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chainId: string;
                    protocol: string;
                    poolId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                intervalSeconds?: number;
                                bucketStart?: number;
                                open?: string;
                                high?: string;
                                low?: string;
                                close?: string;
                                tradeCount?: number;
                            }[];
                            complete?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tokens?: {
                                chainId?: number;
                                tokenAddress?: string;
                                name?: string | null;
                                symbol?: string | null;
                                logoUri?: string | null;
                                platform?: string;
                            }[];
                            pools?: {
                                chainId?: number;
                                protocol?: string;
                                poolId?: string;
                                fee?: number;
                                currency0?: string;
                                currency1?: string;
                                launchToken?: {
                                    address?: string;
                                    name?: string | null;
                                    symbol?: string | null;
                                    logoUri?: string | null;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
